import { StatusBar, StyleSheet } from "react-native";

export default StyleSheet.create({
  background: {
    
    alignSelf: "center",
    borderColor: "#000",
    borderStyle: "solid",
    borderWidth: 2,
    borderRadius: 30,
    backgroundColor: "#fff2cc",
    height: 730,
    width: "80%",
  },
  text: {
    textAlign: "center",
    fontSize: 25,
    marginTop: 5,
    marginBottom: 10,
  },
  input: {
    textAlign: "center",
    fontSize: 20,
    marginBottom: 5,
    marginLeft: 20,
    marginRight: 20,
    height: 50,
    borderColor: "#000",
    borderStyle: "solid",
    borderWidth: 2,
    borderRadius: 30,
    backgroundColor: "#fff",
  },
  input_Linha_Coluna: {
    textAlign: "center",
    fontSize: 20,
    marginBottom: 5,
    marginLeft: 20,
    marginRight: 20,
    height: 50,
    borderColor: "#000",
    borderStyle: "solid",
    borderWidth: 2,
    backgroundColor: "#fff",
  },
  bordadura: {
    textAlign: "center",
    fontSize: 25,
    marginTop: 5,
    marginBottom: 2,
   fontWeight: "bold",
  },
  botao: {
    marginTop: 35,
    alignSelf: "center",
    borderColor: "#000",
    borderStyle: "solid",
    borderWidth: 2,
    borderRadius: 30,
    backgroundColor: "#32CD32",
    height: 50,
    width: "80%",
    marginBottom: 10,
  },
  text_botao: {
    textAlign: "center",
    fontSize: 25,
    marginTop: 5,
    marginBottom: 2,
    fontWeight: "bold",
    color: "#FFF",
  },

});
